// <auto-generated />
using System;
using DbOracle.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace DbOracle.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20230903134313_design")]
    partial class design
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("DESIGN")
                .UseCollation("USING_NLS_COMP")
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DbOracle.Models.AccountingSubject", b =>
                {
                    b.Property<decimal>("AccountSubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("ACCOUNT_SUBJECT_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("AccountSubjectId"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("AMOUNT");

                    b.Property<string>("Category")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(128)")
                        .HasColumnName("CATEGORY");

                    b.Property<string>("Credit")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(128)")
                        .HasColumnName("CREDIT");

                    b.Property<string>("Debit")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(128)")
                        .HasColumnName("DEBIT");

                    b.Property<decimal?>("EmpId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("EMP_ID");

                    b.HasKey("AccountSubjectId")
                        .HasName("SYS_C008866");

                    b.HasIndex("EmpId");

                    b.ToTable("ACCOUNTING_SUBJECTS", "DESIGN");
                });

            modelBuilder.Entity("DbOracle.Models.Application", b =>
                {
                    b.Property<decimal>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("APPLICATION_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ApplicationId"));

                    b.Property<string>("ApplicationContent")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(128)")
                        .HasColumnName("APPLICATION_CONTENT");

                    b.Property<DateTime?>("ApplicationTime")
                        .HasColumnType("DATE")
                        .HasColumnName("APPLICATION_TIME");

                    b.Property<string>("ApplicationType")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("APPLICATION_TYPE");

                    b.Property<decimal?>("EmployeeId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("EMPLOYEE_ID");

                    b.Property<string>("IfApprove")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("IF_APPROVE");

                    b.HasKey("ApplicationId")
                        .HasName("SYS_C008857");

                    b.HasIndex("EmployeeId");

                    b.ToTable("APPLICATION", "DESIGN");
                });

            modelBuilder.Entity("DbOracle.Models.AssetsInformation", b =>
                {
                    b.Property<decimal>("AssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("ASSET_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("AssetId"));

                    b.Property<decimal?>("AccountSubjectId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("ACCOUNT_SUBJECT_ID");

                    b.Property<string>("AssetsCategory")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("ASSETS_CATEGORY");

                    b.Property<string>("AssetsName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("ASSETS_NAME");

                    b.Property<decimal?>("LocationId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("LOCATION_ID");

                    b.Property<long?>("OriginalAssetsAmount")
                        .HasPrecision(12)
                        .HasColumnType("NUMBER(12)")
                        .HasColumnName("ORIGINAL_ASSETS_AMOUNT");

                    b.Property<DateTime?>("RegistrationTime")
                        .HasPrecision(6)
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("REGISTRATION_TIME");

                    b.Property<string>("Valid")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(10)")
                        .HasColumnName("VALID")
                        .HasDefaultValueSql("'Y'");

                    b.HasKey("AssetId")
                        .HasName("SYS_C008874");

                    b.HasIndex("AccountSubjectId");

                    b.HasIndex("LocationId");

                    b.ToTable("ASSETS_INFORMATION", "DESIGN");
                });

            modelBuilder.Entity("DbOracle.Models.AssetsSummarize", b =>
                {
                    b.Property<decimal>("AssetsSummarizeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("ASSET_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("AssetsSummarizeId"));

                    b.Property<decimal?>("AccountSubjectId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("ACCOUNT_SUBJECT_ID");

                    b.Property<long?>("AssetPresentValue")
                        .HasPrecision(12)
                        .HasColumnType("NUMBER(12)")
                        .HasColumnName("ASSET_PRESENT_VALUE");

                    b.Property<long?>("AssetsAmount")
                        .HasPrecision(12)
                        .HasColumnType("NUMBER(12)")
                        .HasColumnName("ASSETS_AMOUNT");

                    b.Property<long?>("AssetsDepreciation")
                        .HasPrecision(12)
                        .HasColumnType("NUMBER(12)")
                        .HasColumnName("ASSETS_DEPRECIATION");

                    b.Property<decimal?>("ResponsPersonId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("RESPONS_PERSON_ID");

                    b.HasKey("AssetsSummarizeId")
                        .HasName("SYS_C008877");

                    b.HasIndex("AccountSubjectId");

                    b.ToTable("ASSETS_SUMMARIZE", "DESIGN");
                });

            modelBuilder.Entity("DbOracle.Models.Assignment", b =>
                {
                    b.Property<decimal>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("ASSIGNMENT_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("AssignmentId"));

                    b.Property<string>("AssignmentName")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(128)")
                        .HasColumnName("ASSIGNMENT_NAME");

                    b.Property<string>("AssignmentNote")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(128)")
                        .HasColumnName("ASSIGNMENT_NOTE");

                    b.Property<decimal?>("DepartmentId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("DEPARTMENT_ID");

                    b.HasKey("AssignmentId")
                        .HasName("SYS_C008793");

                    b.HasIndex("DepartmentId");

                    b.ToTable("ASSIGNMENT", "DESIGN");
                });

            modelBuilder.Entity("DbOracle.Models.AttendanceInformation", b =>
                {
                    b.Property<decimal>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("ATTENDANCE_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("AttendanceId"));

                    b.Property<decimal?>("AbsentDays")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("ABSENT_DAYS");

                    b.Property<decimal?>("ActualAttendanceDays")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("ACTUAL_ATTENDANCE_DAYS");

                    b.Property<decimal?>("EarlyDepartureDays")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("EARLY_DEPARTURE_DAYS");

                    b.Property<decimal?>("EmpId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("EMP_ID");

                    b.Property<decimal?>("ExpectAttendanceDays")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("EXPECT_ATTENDANCE_DAYS");

                    b.Property<decimal?>("LateDays")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("LATE_DAYS");

                    b.Property<decimal?>("Month")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("MONTH");

                    b.Property<decimal?>("PersonalLeaveDays")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("PERSONAL_LEAVE_DAYS");

                    b.Property<decimal?>("SickLeaveDays")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("SICK_LEAVE_DAYS");

                    b.Property<decimal?>("Year")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("YEAR");

                    b.HasKey("AttendanceId")
                        .HasName("SYS_C008862");

                    b.HasIndex("EmpId");

                    b.ToTable("ATTENDANCE_INFORMATION", "DESIGN");
                });

            modelBuilder.Entity("DbOracle.Models.Bill", b =>
                {
                    b.Property<decimal>("BillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("BILL_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("BillId"));

                    b.Property<string>("BillType")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(128)")
                        .HasColumnName("BILL_TYPE");

                    b.Property<decimal?>("FoodCost")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("FOOD_COST");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(128)")
                        .HasColumnName("INVOICE_NUMBER");

                    b.Property<decimal?>("OtherCost")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("OTHER_COST");

                    b.Property<decimal?>("RoomCost")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("ROOM_COST");

                    b.HasKey("BillId")
                        .HasName("SYS_C008804");

                    b.ToTable("BILL", "DESIGN");
                });

            modelBuilder.Entity("DbOracle.Models.Book", b =>
                {
                    b.Property<decimal>("TableId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("TABLE_ID");

                    b.Property<decimal>("CustomerId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("CUSTOMER_ID");

                    b.Property<DateTime>("BookTime")
                        .HasPrecision(6)
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("BOOK_TIME");

                    b.Property<string>("BookStatus")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("BOOK_STATUS");

                    b.Property<string>("Note")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(128)")
                        .HasColumnName("NOTE");

                    b.Property<decimal?>("Num")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("NUM");

                    b.Property<string>("SpecialDemand")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(128)")
                        .HasColumnName("SPECIAL_DEMAND");

                    b.HasKey("TableId", "CustomerId", "BookTime")
                        .HasName("SYS_C008814");

                    b.HasIndex("CustomerId");

                    b.ToTable("BOOK", "DESIGN");
                });

            modelBuilder.Entity("DbOracle.Models.Car", b =>
                {
                    b.Property<string>("CarNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("CAR_NUMBER");

                    b.Property<decimal?>("CustomerId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("CUSTOMER_ID");

                    b.HasKey("CarNumber")
                        .HasName("SYS_C008828");

                    b.HasIndex("CustomerId");

                    b.ToTable("CAR", "DESIGN");
                });

            modelBuilder.Entity("DbOracle.Models.CheckInCheckOut", b =>
                {
                    b.Property<decimal>("CheckInId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("CHECK_IN_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("CheckInId"));

                    b.Property<DateTime?>("CheckInDate")
                        .HasColumnType("DATE")
                        .HasColumnName("CHECK_IN_DATE");

                    b.Property<decimal?>("EmpId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("EMP_ID");

                    b.HasKey("CheckInId")
                        .HasName("SYS_C008864");

                    b.HasIndex("EmpId");

                    b.ToTable("CHECK_IN_CHECK_OUT", "DESIGN");
                });

            modelBuilder.Entity("DbOracle.Models.Checkin", b =>
                {
                    b.Property<decimal>("CustomerId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("CUSTOMER_ID");

                    b.Property<decimal>("RoomId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("ROOM_ID");

                    b.Property<DateTime>("InTime")
                        .HasPrecision(6)
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("IN_TIME");

                    b.Property<DateTime?>("OutTime")
                        .HasPrecision(6)
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("OUT_TIME");

                    b.HasKey("CustomerId", "RoomId", "InTime")
                        .HasName("SYS_C008838");

                    b.HasIndex("RoomId");

                    b.ToTable("CHECKIN", "DESIGN");
                });

            modelBuilder.Entity("DbOracle.Models.Checkrepair", b =>
                {
                    b.Property<decimal>("EmpId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("EMP_ID");

                    b.Property<decimal>("AssetId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("ASSET_ID");

                    b.Property<string>("CheckRepairContent")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(128)")
                        .HasColumnName("CHECK_REPAIR_CONTENT");

                    b.Property<DateTime?>("CheckRepairTime")
                        .HasPrecision(6)
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("CHECK_REPAIR_TIME");

                    b.HasKey("EmpId", "AssetId")
                        .HasName("SYS_C008882");

                    b.HasIndex("AssetId");

                    b.ToTable("CHECKREPAIR", "DESIGN");
                });

            modelBuilder.Entity("DbOracle.Models.Cleaning", b =>
                {
                    b.Property<decimal>("RoomId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("ROOM_ID");

                    b.Property<decimal>("EmpId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("EMP_ID");

                    b.Property<DateTime>("CleaningTime")
                        .HasPrecision(6)
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("CLEANING_TIME");

                    b.HasKey("RoomId", "EmpId", "CleaningTime")
                        .HasName("SYS_C008832");

                    b.HasIndex("EmpId");

                    b.ToTable("CLEANING", "DESIGN");
                });

            modelBuilder.Entity("DbOracle.Models.Complaint", b =>
                {
                    b.Property<decimal>("ComplaintId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("COMPLAINT_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ComplaintId"));

                    b.Property<string>("ComplaintType")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("COMPLAINT_TYPE");

                    b.Property<decimal?>("CustomerId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("CUSTOMER_ID");

                    b.Property<string>("Description")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(128)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("Feedback")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("FEEDBACK");

                    b.Property<string>("Result")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("RESULT");

                    b.Property<DateTime?>("SubmitTime")
                        .HasPrecision(6)
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("SUBMIT_TIME");

                    b.Property<string>("Way")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("WAY");

                    b.HasKey("ComplaintId")
                        .HasName("SYS_C008819");

                    b.HasIndex("CustomerId");

                    b.ToTable("COMPLAINT", "DESIGN");
                });

            modelBuilder.Entity("DbOracle.Models.Consume", b =>
                {
                    b.Property<decimal>("DepartmentId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("DEPARTMENT_ID");

                    b.Property<decimal>("GoodsId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("GOODS_ID");

                    b.Property<decimal?>("ConsumeQuantity")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("CONSUME_QUANTITY");

                    b.HasKey("DepartmentId", "GoodsId")
                        .HasName("SYS_C008868");

                    b.HasIndex("GoodsId");

                    b.ToTable("CONSUME", "DESIGN");
                });

            modelBuilder.Entity("DbOracle.Models.ConsumptionRecord", b =>
                {
                    b.Property<decimal>("ConsumeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("CONSUME_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ConsumeId"));

                    b.Property<decimal?>("BillId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("BILL_ID");

                    b.Property<decimal?>("ConsumeAmount")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("CONSUME_AMOUNT");

                    b.Property<DateTime?>("ConsumeTime")
                        .HasPrecision(6)
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("CONSUME_TIME");

                    b.Property<string>("ConsumeType")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(30)")
                        .HasColumnName("CONSUME_TYPE");

                    b.Property<decimal?>("EmployeeId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("EMPLOYEE_ID");

                    b.Property<decimal?>("RoomId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("ROOM_ID");

                    b.HasKey("ConsumeId")
                        .HasName("SYS_C008848");

                    b.HasIndex("BillId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("RoomId");

                    b.ToTable("CONSUMPTION_RECORDS", "DESIGN");
                });

            modelBuilder.Entity("DbOracle.Models.Customer", b =>
                {
                    b.Property<decimal>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("CUSTOMER_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("CustomerId"));

                    b.Property<string>("CreditGrade")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("CREDIT_GRADE");

                    b.Property<string>("Gender")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(6)")
                        .HasColumnName("GENDER");

                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("ID");

                    b.Property<string>("MemberGrade")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("MEMBER_GRADE");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(128)")
                        .HasColumnName("NAME");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("PHONE");

                    b.HasKey("CustomerId")
                        .HasName("SYS_C008803");

                    b.ToTable("CUSTOMER", "DESIGN");
                });

            modelBuilder.Entity("DbOracle.Models.Department", b =>
                {
                    b.Property<decimal>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("DEPARTMENT_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("DepartmentId"));

                    b.Property<string>("DepartmentName")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("DEPARTMENT_NAME");

                    b.Property<decimal?>("NumberOfPeople")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("NUMBER_OF_PEOPLE");

                    b.HasKey("DepartmentId")
                        .HasName("SYS_C008792");

                    b.ToTable("DEPARTMENT", "DESIGN");
                });

            modelBuilder.Entity("DbOracle.Models.Dish", b =>
                {
                    b.Property<decimal>("DishId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("DISH_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("DishId"));

                    b.Property<string>("DishName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("DISH_NAME");

                    b.Property<decimal?>("DishPrice")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("DISH_PRICE");

                    b.Property<string>("DishTaste")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(30)")
                        .HasColumnName("DISH_TASTE");

                    b.HasKey("DishId")
                        .HasName("SYS_C008802");

                    b.ToTable("DISH", "DESIGN");
                });

            modelBuilder.Entity("DbOracle.Models.Employee", b =>
                {
                    b.Property<decimal>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("EMPLOYEE_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("EmployeeId"));

                    b.Property<string>("Account")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("ACCOUNT");

                    b.Property<byte?>("Age")
                        .HasPrecision(3)
                        .HasColumnType("NUMBER(3)")
                        .HasColumnName("AGE");

                    b.Property<string>("BankName")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(128)")
                        .HasColumnName("BANK_NAME");

                    b.Property<decimal?>("BasePay")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("BASE_PAY");

                    b.Property<string>("CreditCardNumber")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(30)")
                        .HasColumnName("CREDIT_CARD_NUMBER");

                    b.Property<DateTime?>("EntryTime")
                        .HasColumnType("DATE")
                        .HasColumnName("ENTRY_TIME");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(128)")
                        .HasColumnName("NAME");

                    b.Property<string>("Password")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(40)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("PHONE_NUMBER");

                    b.Property<decimal?>("PostId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("POST_ID");

                    b.Property<string>("Sex")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(6)")
                        .HasColumnName("SEX");

                    b.HasKey("EmployeeId")
                        .HasName("SYS_C008797");

                    b.HasIndex("PostId");

                    b.ToTable("EMPLOYEE", "DESIGN");
                });

            modelBuilder.Entity("DbOracle.Models.EnterExit", b =>
                {
                    b.Property<decimal>("InfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("INFO_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("InfoId"));

                    b.Property<string>("CarNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("CAR_NUMBER");

                    b.Property<DateTime?>("EnterTime")
                        .HasPrecision(6)
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("ENTER_TIME");

                    b.Property<DateTime?>("ExitTime")
                        .HasPrecision(6)
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("EXIT_TIME");

                    b.HasKey("InfoId")
                        .HasName("SYS_C008855");

                    b.HasIndex("CarNumber");

                    b.ToTable("ENTER_EXIT", "DESIGN");
                });

            modelBuilder.Entity("DbOracle.Models.Good", b =>
                {
                    b.Property<decimal>("GoodsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("GOODS_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("GoodsId"));

                    b.Property<string>("Category")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(30)")
                        .HasColumnName("CATEGORY");

                    b.Property<string>("GoodsName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("GOODS_NAME");

                    b.Property<decimal?>("Inventory")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("INVENTORY");

                    b.HasKey("GoodsId")
                        .HasName("SYS_C008800");

                    b.ToTable("GOODS", "DESIGN");
                });

            modelBuilder.Entity("DbOracle.Models.Location", b =>
                {
                    b.Property<decimal>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("LOCATION_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("LocationId"));

                    b.Property<decimal?>("Floor")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("FLOOR");

                    b.Property<string>("Note")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(128)")
                        .HasColumnName("NOTE");

                    b.Property<decimal?>("RoomId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("ROOM_ID");

                    b.HasKey("LocationId")
                        .HasName("SYS_C008871");

                    b.HasIndex("RoomId");

                    b.ToTable("LOCATION", "DESIGN");
                });

            modelBuilder.Entity("DbOracle.Models.Maintain", b =>
                {
                    b.Property<decimal>("RoomId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("ROOM_ID");

                    b.Property<decimal>("EmpId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("EMP_ID");

                    b.Property<DateTime>("MaintainTime")
                        .HasPrecision(6)
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("MAINTAIN_TIME");

                    b.Property<string>("Object")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(128)")
                        .HasColumnName("OBJECT");

                    b.Property<string>("Result")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(128)")
                        .HasColumnName("RESULT");

                    b.HasKey("RoomId", "EmpId", "MaintainTime")
                        .HasName("SYS_C008845");

                    b.HasIndex("EmpId");

                    b.ToTable("MAINTAIN", "DESIGN");
                });

            modelBuilder.Entity("DbOracle.Models.Myorder", b =>
                {
                    b.Property<decimal>("TableId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("TABLE_ID");

                    b.Property<decimal>("DishId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("DISH_ID");

                    b.Property<DateTime>("OrderTime")
                        .HasPrecision(6)
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("ORDER_TIME");

                    b.Property<decimal?>("ConsumptionRecordId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("CONSUMPTION_RECORD_ID");

                    b.Property<string>("OrderStatus")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(30)")
                        .HasColumnName("ORDER_STATUS");

                    b.HasKey("TableId", "DishId", "OrderTime")
                        .HasName("SYS_C008810");

                    b.HasIndex("ConsumptionRecordId");

                    b.HasIndex("DishId");

                    b.ToTable("MYORDER", "DESIGN");
                });

            modelBuilder.Entity("DbOracle.Models.Mytable", b =>
                {
                    b.Property<decimal>("TableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("TABLE_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("TableId"));

                    b.Property<decimal?>("Available")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("AVAILABLE");

                    b.Property<decimal?>("Bookable")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("BOOKABLE");

                    b.Property<decimal?>("CapacityNum")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("CAPACITY_NUM");

                    b.Property<string>("Note")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(128)")
                        .HasColumnName("NOTE");

                    b.Property<string>("TableLocation")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(30)")
                        .HasColumnName("TABLE_LOCATION");

                    b.Property<string>("TableStatus")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(30)")
                        .HasColumnName("TABLE_STATUS");

                    b.Property<string>("TableType")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(30)")
                        .HasColumnName("TABLE_TYPE");

                    b.HasKey("TableId")
                        .HasName("SYS_C008801");

                    b.ToTable("MYTABLE", "DESIGN");
                });

            modelBuilder.Entity("DbOracle.Models.ParkPlace", b =>
                {
                    b.Property<decimal>("ParkingSpaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("PARKING_SPACE_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ParkingSpaceId"));

                    b.Property<string>("Area")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(128)")
                        .HasColumnName("AREA");

                    b.Property<string>("Status")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(128)")
                        .HasColumnName("STATUS");

                    b.Property<string>("Type")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(128)")
                        .HasColumnName("TYPE");

                    b.HasKey("ParkingSpaceId")
                        .HasName("SYS_C008826");

                    b.HasIndex("Type");

                    b.ToTable("PARK_PLACE", "DESIGN");
                });

            modelBuilder.Entity("DbOracle.Models.Parking", b =>
                {
                    b.Property<decimal>("ParkingSpaceId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("PARKING_SPACE_ID");

                    b.Property<string>("CarNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("CAR_NUMBER");

                    b.Property<DateTime>("StartTime")
                        .HasPrecision(6)
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("START_TIME");

                    b.Property<DateTime?>("EndTime")
                        .HasPrecision(6)
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("END_TIME");

                    b.HasKey("ParkingSpaceId", "CarNumber", "StartTime")
                        .HasName("SYS_C008852");

                    b.HasIndex("CarNumber");

                    b.ToTable("PARKING", "DESIGN");
                });

            modelBuilder.Entity("DbOracle.Models.Pay", b =>
                {
                    b.Property<decimal>("CustomerId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("CUSTOMER_ID");

                    b.Property<decimal>("BillId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("BILL_ID");

                    b.Property<decimal?>("PayCount")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("PAY_COUNT");

                    b.Property<DateTime?>("PayTime")
                        .HasPrecision(6)
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("PAY_TIME");

                    b.Property<string>("PayWay")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(128)")
                        .HasColumnName("PAY_WAY");

                    b.Property<string>("Status")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(128)")
                        .HasColumnName("STATUS");

                    b.HasKey("CustomerId", "BillId")
                        .HasName("SYS_C008823");

                    b.HasIndex("BillId");

                    b.ToTable("PAY", "DESIGN");
                });

            modelBuilder.Entity("DbOracle.Models.Post", b =>
                {
                    b.Property<decimal>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("POST_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("PostId"));

                    b.Property<decimal?>("AccumulationFunds")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("ACCUMULATION_FUNDS");

                    b.Property<string>("Authority")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(128)")
                        .HasColumnName("AUTHORITY");

                    b.Property<decimal?>("DepartmentId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("DEPARTMENT_ID");

                    b.Property<string>("Insurance")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(128)")
                        .HasColumnName("INSURANCE");

                    b.Property<string>("PaymentBase")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(128)")
                        .HasColumnName("PAYMENT_BASE");

                    b.Property<string>("PaymentType")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(128)")
                        .HasColumnName("PAYMENT_TYPE");

                    b.Property<string>("PositionLevel")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("POSITION_LEVEL");

                    b.Property<decimal?>("PositionSalary")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("POSITION_SALARY");

                    b.Property<string>("PostName")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(30)")
                        .HasColumnName("POST_NAME");

                    b.HasKey("PostId")
                        .HasName("SYS_C008795");

                    b.HasIndex("DepartmentId");

                    b.ToTable("POST", "DESIGN");
                });

            modelBuilder.Entity("DbOracle.Models.Purchase", b =>
                {
                    b.Property<decimal>("GoodsId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("GOODS_ID");

                    b.Property<decimal>("EmployeeId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("EMPLOYEE_ID");

                    b.Property<decimal>("SupplierId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("SUPPLIER_ID");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("DATE")
                        .HasColumnName("PURCHASE_DATE");

                    b.Property<decimal>("PurchaseQuantity")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("PURCHASE_QUANTITY");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("UNIT_PRICE");

                    b.HasKey("GoodsId", "EmployeeId", "SupplierId")
                        .HasName("SYS_C008859");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("SupplierId");

                    b.ToTable("PURCHASE", "DESIGN");
                });

            modelBuilder.Entity("DbOracle.Models.Room", b =>
                {
                    b.Property<decimal>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("ROOM_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("RoomId"));

                    b.Property<decimal?>("RoomNum")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("ROOM_NUM");

                    b.Property<string>("RoomPhone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("ROOM_PHONE");

                    b.Property<string>("Status")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(30)")
                        .HasColumnName("STATUS");

                    b.Property<decimal?>("TypeId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("TYPE_ID");

                    b.HasKey("RoomId")
                        .HasName("SYS_C008821");

                    b.HasIndex("TypeId");

                    b.ToTable("ROOM", "DESIGN");
                });

            modelBuilder.Entity("DbOracle.Models.Roomorder", b =>
                {
                    b.Property<decimal>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("ORDER_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("OrderId"));

                    b.Property<DateTime?>("CreateTime")
                        .HasPrecision(6)
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("CREATE_TIME");

                    b.Property<decimal?>("CustomerId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("CUSTOMER_ID");

                    b.Property<decimal?>("EmpId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("EMP_ID");

                    b.Property<DateTime?>("ExpectInTime")
                        .HasColumnType("DATE")
                        .HasColumnName("EXPECT_IN_TIME");

                    b.Property<DateTime?>("ExpectOutTime")
                        .HasColumnType("DATE")
                        .HasColumnName("EXPECT_OUT_TIME");

                    b.Property<string>("Note")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(128)")
                        .HasColumnName("NOTE");

                    b.Property<decimal?>("Num")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("NUM");

                    b.Property<string>("OrderStatus")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(30)")
                        .HasColumnName("ORDER_STATUS");

                    b.Property<decimal?>("Price")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("PRICE");

                    b.Property<decimal?>("TypeId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("TYPE_ID");

                    b.HasKey("OrderId")
                        .HasName("SYS_C008841");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EmpId");

                    b.HasIndex("TypeId");

                    b.ToTable("ROOMORDER", "DESIGN");
                });

            modelBuilder.Entity("DbOracle.Models.Roomtype", b =>
                {
                    b.Property<decimal>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("TYPE_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("TypeId"));

                    b.Property<string>("Note")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(128)")
                        .HasColumnName("NOTE");

                    b.Property<decimal?>("Price")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("PRICE");

                    b.Property<decimal?>("Remaining")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("REMAINING");

                    b.Property<string>("TypeName")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(30)")
                        .HasColumnName("TYPE_NAME");

                    b.HasKey("TypeId")
                        .HasName("SYS_C008806");

                    b.ToTable("ROOMTYPE", "DESIGN");
                });

            modelBuilder.Entity("DbOracle.Models.Salary", b =>
                {
                    b.Property<decimal>("SalaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("ASSETS_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("SalaryId"));

                    b.Property<decimal?>("Bonus")
                        .HasColumnType("NUMBER(12,2)")
                        .HasColumnName("BONUS");

                    b.Property<decimal?>("Commission")
                        .HasColumnType("NUMBER(12,2)")
                        .HasColumnName("COMMISSION");

                    b.Property<decimal?>("EarlyDepartureDeduction")
                        .HasColumnType("NUMBER(12,2)")
                        .HasColumnName("EARLY_DEPARTURE_DEDUCTION");

                    b.Property<decimal?>("EmpId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("EMP_ID");

                    b.Property<decimal?>("GrossSalary")
                        .HasColumnType("NUMBER(12,2)")
                        .HasColumnName("GROSS_SALARY");

                    b.Property<decimal?>("HolidayAllowance")
                        .HasColumnType("NUMBER(12,2)")
                        .HasColumnName("HOLIDAY_ALLOWANCE");

                    b.Property<decimal?>("IncomeTax")
                        .HasColumnType("NUMBER(12,2)")
                        .HasColumnName("INCOME_TAX");

                    b.Property<decimal?>("LateDeduction")
                        .HasColumnType("NUMBER(12,2)")
                        .HasColumnName("LATE_DEDUCTION");

                    b.Property<decimal?>("Month")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("MONTH");

                    b.Property<decimal?>("NetSalary")
                        .HasColumnType("NUMBER(12,2)")
                        .HasColumnName("NET_SALARY");

                    b.Property<decimal?>("OtherAllowance")
                        .HasColumnType("NUMBER(12,2)")
                        .HasColumnName("OTHER_ALLOWANCE");

                    b.Property<decimal?>("OvertimePay")
                        .HasColumnType("NUMBER(12,2)")
                        .HasColumnName("OVERTIME_PAY");

                    b.Property<decimal?>("RewardAmount")
                        .HasColumnType("NUMBER(12,2)")
                        .HasColumnName("REWARD_AMOUNT");

                    b.Property<string>("RewardType")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(128)")
                        .HasColumnName("REWARD_TYPE");

                    b.Property<decimal?>("SocialInsurance")
                        .HasColumnType("NUMBER(12,2)")
                        .HasColumnName("SOCIAL_INSURANCE");

                    b.Property<decimal?>("Year")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("YEAR");

                    b.Property<decimal?>("YearEndBonus")
                        .HasColumnType("NUMBER(12,2)")
                        .HasColumnName("YEAR_END_BONUS");

                    b.HasKey("SalaryId")
                        .HasName("SYS_C008830");

                    b.HasIndex("EmpId");

                    b.ToTable("SALARY", "DESIGN");
                });

            modelBuilder.Entity("DbOracle.Models.Scrap", b =>
                {
                    b.Property<decimal>("EmpId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("EMP_ID");

                    b.Property<decimal>("AssetId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("ASSET_ID");

                    b.Property<string>("ScrapReason")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(128)")
                        .HasColumnName("SCRAP_REASON");

                    b.Property<DateTime?>("ScrapTime")
                        .HasPrecision(6)
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("SCRAP_TIME");

                    b.HasKey("EmpId", "AssetId")
                        .HasName("SYS_C008879");

                    b.HasIndex("AssetId");

                    b.ToTable("SCRAP", "DESIGN");
                });

            modelBuilder.Entity("DbOracle.Models.Service", b =>
                {
                    b.Property<decimal>("CustomerId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("CUSTOMER_ID");

                    b.Property<decimal>("EmpId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("EMP_ID");

                    b.Property<DateTime>("ServiceTime")
                        .HasPrecision(6)
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("SERVICE_TIME");

                    b.Property<string>("Result")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(128)")
                        .HasColumnName("RESULT");

                    b.Property<string>("ServiceType")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(30)")
                        .HasColumnName("SERVICE_TYPE");

                    b.HasKey("CustomerId", "EmpId", "ServiceTime")
                        .HasName("SYS_C008835");

                    b.HasIndex("EmpId");

                    b.ToTable("SERVICE", "DESIGN");
                });

            modelBuilder.Entity("DbOracle.Models.Staging", b =>
                {
                    b.Property<decimal>("LuggageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("LUGGAGE_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("LuggageId"));

                    b.Property<decimal?>("CustomerId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("CUSTOMER_ID");

                    b.Property<DateTime?>("FetchTime")
                        .HasPrecision(6)
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("FETCH_TIME");

                    b.Property<string>("LuggageType")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(128)")
                        .HasColumnName("LUGGAGE_TYPE");

                    b.Property<DateTime?>("StagingTime")
                        .HasPrecision(6)
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("STAGING_TIME");

                    b.HasKey("LuggageId")
                        .HasName("SYS_C008817");

                    b.HasIndex("CustomerId");

                    b.ToTable("STAGING", "DESIGN");
                });

            modelBuilder.Entity("DbOracle.Models.Supplier", b =>
                {
                    b.Property<decimal>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("SUPPLIER_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("SupplierId"));

                    b.Property<string>("Address")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(128)")
                        .HasColumnName("ADDRESS");

                    b.Property<string>("SupplierPhone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("SUPPLIER_PHONE");

                    b.HasKey("SupplierId")
                        .HasName("SYS_C008799");

                    b.ToTable("SUPPLIER", "DESIGN");
                });

            modelBuilder.Entity("DbOracle.Models.UnitPrice", b =>
                {
                    b.Property<string>("ParkingPlaceType")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(30)")
                        .HasColumnName("PARKING_PLACE_TYPE");

                    b.Property<decimal?>("MemberPrice")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("MEMBER_PRICE");

                    b.Property<decimal?>("NotMemberPrice")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("NOT_MEMBER_PRICE");

                    b.HasKey("ParkingPlaceType")
                        .HasName("SYS_C008805");

                    b.ToTable("UNIT_PRICE", "DESIGN");
                });

            modelBuilder.Entity("DbOracle.Models.AccountingSubject", b =>
                {
                    b.HasOne("DbOracle.Models.Employee", "Emp")
                        .WithMany("AccountingSubjects")
                        .HasForeignKey("EmpId")
                        .HasConstraintName("SYS_C008867");

                    b.Navigation("Emp");
                });

            modelBuilder.Entity("DbOracle.Models.Application", b =>
                {
                    b.HasOne("DbOracle.Models.Employee", "Employee")
                        .WithMany("Applications")
                        .HasForeignKey("EmployeeId")
                        .HasConstraintName("SYS_C008858");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("DbOracle.Models.AssetsInformation", b =>
                {
                    b.HasOne("DbOracle.Models.AccountingSubject", "AccountSubject")
                        .WithMany("AssetsInformations")
                        .HasForeignKey("AccountSubjectId")
                        .HasConstraintName("SYS_C008875");

                    b.HasOne("DbOracle.Models.Location", "Location")
                        .WithMany("AssetsInformations")
                        .HasForeignKey("LocationId")
                        .HasConstraintName("SYS_C008876");

                    b.Navigation("AccountSubject");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("DbOracle.Models.AssetsSummarize", b =>
                {
                    b.HasOne("DbOracle.Models.AccountingSubject", "AccountSubject")
                        .WithMany("AssetsSummarizes")
                        .HasForeignKey("AccountSubjectId")
                        .HasConstraintName("SYS_C008878");

                    b.Navigation("AccountSubject");
                });

            modelBuilder.Entity("DbOracle.Models.Assignment", b =>
                {
                    b.HasOne("DbOracle.Models.Department", "Department")
                        .WithMany("Assignments")
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("SYS_C008794");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("DbOracle.Models.AttendanceInformation", b =>
                {
                    b.HasOne("DbOracle.Models.Employee", "Emp")
                        .WithMany("AttendanceInformations")
                        .HasForeignKey("EmpId")
                        .HasConstraintName("SYS_C008863");

                    b.Navigation("Emp");
                });

            modelBuilder.Entity("DbOracle.Models.Book", b =>
                {
                    b.HasOne("DbOracle.Models.Customer", "Customer")
                        .WithMany("Books")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("SYS_C008816");

                    b.HasOne("DbOracle.Models.Mytable", "Table")
                        .WithMany("Books")
                        .HasForeignKey("TableId")
                        .IsRequired()
                        .HasConstraintName("SYS_C008815");

                    b.Navigation("Customer");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("DbOracle.Models.Car", b =>
                {
                    b.HasOne("DbOracle.Models.Customer", "Customer")
                        .WithMany("Cars")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("SYS_C008829");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("DbOracle.Models.CheckInCheckOut", b =>
                {
                    b.HasOne("DbOracle.Models.Employee", "Emp")
                        .WithMany("CheckInCheckOuts")
                        .HasForeignKey("EmpId")
                        .HasConstraintName("SYS_C008865");

                    b.Navigation("Emp");
                });

            modelBuilder.Entity("DbOracle.Models.Checkin", b =>
                {
                    b.HasOne("DbOracle.Models.Customer", "Customer")
                        .WithMany("Checkins")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("SYS_C008839");

                    b.HasOne("DbOracle.Models.Room", "Room")
                        .WithMany("Checkins")
                        .HasForeignKey("RoomId")
                        .IsRequired()
                        .HasConstraintName("SYS_C008840");

                    b.Navigation("Customer");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("DbOracle.Models.Checkrepair", b =>
                {
                    b.HasOne("DbOracle.Models.AssetsInformation", "Asset")
                        .WithMany("Checkrepairs")
                        .HasForeignKey("AssetId")
                        .IsRequired()
                        .HasConstraintName("SYS_C008884");

                    b.HasOne("DbOracle.Models.Employee", "Emp")
                        .WithMany("Checkrepairs")
                        .HasForeignKey("EmpId")
                        .IsRequired()
                        .HasConstraintName("SYS_C008883");

                    b.Navigation("Asset");

                    b.Navigation("Emp");
                });

            modelBuilder.Entity("DbOracle.Models.Cleaning", b =>
                {
                    b.HasOne("DbOracle.Models.Employee", "Emp")
                        .WithMany("Cleanings")
                        .HasForeignKey("EmpId")
                        .IsRequired()
                        .HasConstraintName("SYS_C008834");

                    b.HasOne("DbOracle.Models.Room", "Room")
                        .WithMany("Cleanings")
                        .HasForeignKey("RoomId")
                        .IsRequired()
                        .HasConstraintName("SYS_C008833");

                    b.Navigation("Emp");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("DbOracle.Models.Complaint", b =>
                {
                    b.HasOne("DbOracle.Models.Customer", "Customer")
                        .WithMany("Complaints")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("SYS_C008820");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("DbOracle.Models.Consume", b =>
                {
                    b.HasOne("DbOracle.Models.Department", "Department")
                        .WithMany("Consumes")
                        .HasForeignKey("DepartmentId")
                        .IsRequired()
                        .HasConstraintName("SYS_C008869");

                    b.HasOne("DbOracle.Models.Good", "Goods")
                        .WithMany("Consumes")
                        .HasForeignKey("GoodsId")
                        .IsRequired()
                        .HasConstraintName("SYS_C008870");

                    b.Navigation("Department");

                    b.Navigation("Goods");
                });

            modelBuilder.Entity("DbOracle.Models.ConsumptionRecord", b =>
                {
                    b.HasOne("DbOracle.Models.Bill", "Bill")
                        .WithMany("ConsumptionRecords")
                        .HasForeignKey("BillId")
                        .HasConstraintName("SYS_C008850");

                    b.HasOne("DbOracle.Models.Employee", "Employee")
                        .WithMany("ConsumptionRecords")
                        .HasForeignKey("EmployeeId")
                        .HasConstraintName("SYS_C008851");

                    b.HasOne("DbOracle.Models.Room", "Room")
                        .WithMany("ConsumptionRecords")
                        .HasForeignKey("RoomId")
                        .HasConstraintName("SYS_C008849");

                    b.Navigation("Bill");

                    b.Navigation("Employee");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("DbOracle.Models.Employee", b =>
                {
                    b.HasOne("DbOracle.Models.Post", "Post")
                        .WithMany("Employees")
                        .HasForeignKey("PostId")
                        .HasConstraintName("SYS_C008798");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("DbOracle.Models.EnterExit", b =>
                {
                    b.HasOne("DbOracle.Models.Car", "CarNumberNavigation")
                        .WithMany("EnterExits")
                        .HasForeignKey("CarNumber")
                        .HasConstraintName("SYS_C008856");

                    b.Navigation("CarNumberNavigation");
                });

            modelBuilder.Entity("DbOracle.Models.Location", b =>
                {
                    b.HasOne("DbOracle.Models.Room", "Room")
                        .WithMany("Locations")
                        .HasForeignKey("RoomId")
                        .HasConstraintName("SYS_C008872");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("DbOracle.Models.Maintain", b =>
                {
                    b.HasOne("DbOracle.Models.Employee", "Emp")
                        .WithMany("Maintains")
                        .HasForeignKey("EmpId")
                        .IsRequired()
                        .HasConstraintName("SYS_C008847");

                    b.HasOne("DbOracle.Models.Room", "Room")
                        .WithMany("Maintains")
                        .HasForeignKey("RoomId")
                        .IsRequired()
                        .HasConstraintName("SYS_C008846");

                    b.Navigation("Emp");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("DbOracle.Models.Myorder", b =>
                {
                    b.HasOne("DbOracle.Models.ConsumptionRecord", "ConsumptionRecord")
                        .WithMany("Myorders")
                        .HasForeignKey("ConsumptionRecordId")
                        .HasConstraintName("SYS_C008813");

                    b.HasOne("DbOracle.Models.Dish", "Dish")
                        .WithMany("Myorders")
                        .HasForeignKey("DishId")
                        .IsRequired()
                        .HasConstraintName("SYS_C008812");

                    b.HasOne("DbOracle.Models.Mytable", "Table")
                        .WithMany("Myorders")
                        .HasForeignKey("TableId")
                        .IsRequired()
                        .HasConstraintName("SYS_C008811");

                    b.Navigation("ConsumptionRecord");

                    b.Navigation("Dish");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("DbOracle.Models.ParkPlace", b =>
                {
                    b.HasOne("DbOracle.Models.UnitPrice", "TypeNavigation")
                        .WithMany("ParkPlaces")
                        .HasForeignKey("Type")
                        .HasConstraintName("SYS_C008827");

                    b.Navigation("TypeNavigation");
                });

            modelBuilder.Entity("DbOracle.Models.Parking", b =>
                {
                    b.HasOne("DbOracle.Models.Car", "CarNumberNavigation")
                        .WithMany("Parkings")
                        .HasForeignKey("CarNumber")
                        .IsRequired()
                        .HasConstraintName("SYS_C008854");

                    b.HasOne("DbOracle.Models.ParkPlace", "ParkingSpace")
                        .WithMany("Parkings")
                        .HasForeignKey("ParkingSpaceId")
                        .IsRequired()
                        .HasConstraintName("SYS_C008853");

                    b.Navigation("CarNumberNavigation");

                    b.Navigation("ParkingSpace");
                });

            modelBuilder.Entity("DbOracle.Models.Pay", b =>
                {
                    b.HasOne("DbOracle.Models.Bill", "Bill")
                        .WithMany("Pays")
                        .HasForeignKey("BillId")
                        .IsRequired()
                        .HasConstraintName("SYS_C008825");

                    b.HasOne("DbOracle.Models.Customer", "Customer")
                        .WithMany("Pays")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("SYS_C008824");

                    b.Navigation("Bill");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("DbOracle.Models.Post", b =>
                {
                    b.HasOne("DbOracle.Models.Department", "Department")
                        .WithMany("Posts")
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("SYS_C008796");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("DbOracle.Models.Purchase", b =>
                {
                    b.HasOne("DbOracle.Models.Employee", "Employee")
                        .WithMany("Purchases")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("SYS_C008861");

                    b.HasOne("DbOracle.Models.Good", "Goods")
                        .WithMany("Purchases")
                        .HasForeignKey("GoodsId")
                        .IsRequired()
                        .HasConstraintName("SYS_C008860");

                    b.HasOne("DbOracle.Models.Supplier", "Suppliers")
                        .WithMany("Purchases")
                        .HasForeignKey("SupplierId")
                        .IsRequired()
                        .HasConstraintName("SYS_C008900");

                    b.Navigation("Employee");

                    b.Navigation("Goods");

                    b.Navigation("Suppliers");
                });

            modelBuilder.Entity("DbOracle.Models.Room", b =>
                {
                    b.HasOne("DbOracle.Models.Roomtype", "Type")
                        .WithMany("Rooms")
                        .HasForeignKey("TypeId")
                        .HasConstraintName("SYS_C008822");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("DbOracle.Models.Roomorder", b =>
                {
                    b.HasOne("DbOracle.Models.Customer", "Customer")
                        .WithMany("Roomorders")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("SYS_C008842");

                    b.HasOne("DbOracle.Models.Employee", "Emp")
                        .WithMany("Roomorders")
                        .HasForeignKey("EmpId")
                        .HasConstraintName("SYS_C008844");

                    b.HasOne("DbOracle.Models.Roomtype", "Type")
                        .WithMany("Roomorders")
                        .HasForeignKey("TypeId")
                        .HasConstraintName("SYS_C008843");

                    b.Navigation("Customer");

                    b.Navigation("Emp");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("DbOracle.Models.Salary", b =>
                {
                    b.HasOne("DbOracle.Models.Employee", "Emp")
                        .WithMany("Salaries")
                        .HasForeignKey("EmpId")
                        .HasConstraintName("SYS_C008831");

                    b.Navigation("Emp");
                });

            modelBuilder.Entity("DbOracle.Models.Scrap", b =>
                {
                    b.HasOne("DbOracle.Models.AssetsInformation", "Asset")
                        .WithMany("Scraps")
                        .HasForeignKey("AssetId")
                        .IsRequired()
                        .HasConstraintName("SYS_C008881");

                    b.HasOne("DbOracle.Models.Employee", "Emp")
                        .WithMany("Scraps")
                        .HasForeignKey("EmpId")
                        .IsRequired()
                        .HasConstraintName("SYS_C008880");

                    b.Navigation("Asset");

                    b.Navigation("Emp");
                });

            modelBuilder.Entity("DbOracle.Models.Service", b =>
                {
                    b.HasOne("DbOracle.Models.Customer", "Customer")
                        .WithMany("Services")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("SYS_C008836");

                    b.HasOne("DbOracle.Models.Employee", "Emp")
                        .WithMany("Services")
                        .HasForeignKey("EmpId")
                        .IsRequired()
                        .HasConstraintName("SYS_C008837");

                    b.Navigation("Customer");

                    b.Navigation("Emp");
                });

            modelBuilder.Entity("DbOracle.Models.Staging", b =>
                {
                    b.HasOne("DbOracle.Models.Customer", "Customer")
                        .WithMany("Stagings")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("SYS_C008818");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("DbOracle.Models.AccountingSubject", b =>
                {
                    b.Navigation("AssetsInformations");

                    b.Navigation("AssetsSummarizes");
                });

            modelBuilder.Entity("DbOracle.Models.AssetsInformation", b =>
                {
                    b.Navigation("Checkrepairs");

                    b.Navigation("Scraps");
                });

            modelBuilder.Entity("DbOracle.Models.Bill", b =>
                {
                    b.Navigation("ConsumptionRecords");

                    b.Navigation("Pays");
                });

            modelBuilder.Entity("DbOracle.Models.Car", b =>
                {
                    b.Navigation("EnterExits");

                    b.Navigation("Parkings");
                });

            modelBuilder.Entity("DbOracle.Models.ConsumptionRecord", b =>
                {
                    b.Navigation("Myorders");
                });

            modelBuilder.Entity("DbOracle.Models.Customer", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("Cars");

                    b.Navigation("Checkins");

                    b.Navigation("Complaints");

                    b.Navigation("Pays");

                    b.Navigation("Roomorders");

                    b.Navigation("Services");

                    b.Navigation("Stagings");
                });

            modelBuilder.Entity("DbOracle.Models.Department", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Consumes");

                    b.Navigation("Posts");
                });

            modelBuilder.Entity("DbOracle.Models.Dish", b =>
                {
                    b.Navigation("Myorders");
                });

            modelBuilder.Entity("DbOracle.Models.Employee", b =>
                {
                    b.Navigation("AccountingSubjects");

                    b.Navigation("Applications");

                    b.Navigation("AttendanceInformations");

                    b.Navigation("CheckInCheckOuts");

                    b.Navigation("Checkrepairs");

                    b.Navigation("Cleanings");

                    b.Navigation("ConsumptionRecords");

                    b.Navigation("Maintains");

                    b.Navigation("Purchases");

                    b.Navigation("Roomorders");

                    b.Navigation("Salaries");

                    b.Navigation("Scraps");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("DbOracle.Models.Good", b =>
                {
                    b.Navigation("Consumes");

                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("DbOracle.Models.Location", b =>
                {
                    b.Navigation("AssetsInformations");
                });

            modelBuilder.Entity("DbOracle.Models.Mytable", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("Myorders");
                });

            modelBuilder.Entity("DbOracle.Models.ParkPlace", b =>
                {
                    b.Navigation("Parkings");
                });

            modelBuilder.Entity("DbOracle.Models.Post", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("DbOracle.Models.Room", b =>
                {
                    b.Navigation("Checkins");

                    b.Navigation("Cleanings");

                    b.Navigation("ConsumptionRecords");

                    b.Navigation("Locations");

                    b.Navigation("Maintains");
                });

            modelBuilder.Entity("DbOracle.Models.Roomtype", b =>
                {
                    b.Navigation("Roomorders");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("DbOracle.Models.Supplier", b =>
                {
                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("DbOracle.Models.UnitPrice", b =>
                {
                    b.Navigation("ParkPlaces");
                });
#pragma warning restore 612, 618
        }
    }
}
