server:
  port: 8082
spring:
  application:
    name: performance-service
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://${jike.db.host}:3306/performance-service?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${jike.db.pw}
  cloud:
    nacos:
      server-addr: 118.178.194.247:8848 # nacos地址
mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
knife4j:
  enable: true
  openapi:
    title: 员工表现微服务接口文档
    description: "员工表现接口文档"
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources: