server:
  port: 9000
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 118.178.194.247:8848
    gateway:
      routes:
        - id: frontdesk # 路由规则id，自定义，唯一
          uri: lb://frontdesk-service # 路由的目标服务，lb代表负载均衡，会从注册中心拉取服务列表
          predicates: # 路由断言，判断当前请求是否符合当前规则，符合则路由到目标服务
            - Path=/api/Customer/**,/api/ConsumptionRecord/**,/api/Bill/**,/api/Checkin/**,/api/Cleaning/**,/api/Pay/**,/api/Room/**,/api/Roomorder/**,/api/RoomType/** # 这里是以请求路径作为判断规则
        - id: logistics
          uri: lb://logistics-service
          predicates:
            - Path=/api/Consume/**,/api/Good/**,/api/Purchase/**,/api/Maintain/** # 这里是以请求路径作为判断规则
        - id: canteen
          uri: lb://canteen-service
          predicates:
            - Path=/api/Book/**,/api/Dish/**,/api/MyOrder/**,/api/MyTable/**
        - id: performance
          uri: lb://performance-service
          predicates:
            - Path=/api/AttendanceInformation/**,/api/Salary/** # 这里是以请求路径作为判断规则
        - id: personnel
          uri: lb://personnel-service
          predicates:
            - Path=/api/Department/**,/api/Employee/**,/api/Post/**,/api/Application/**
