CREATE TABLE MYTABLE (
    TABLE_ID INT AUTO_INCREMENT PRIMARY KEY,
    CAPACITY INT CHECK (CAPACITY >= 0),
    TABLE_TYPE VARCHAR(20) NOT NULL,
    TABLE_LOCATION VARCHAR(20) NOT NULL,
    TABLE_STATUS VARCHAR(20) NOT NULL,
    NOTE VARCHAR(50) NOT NULL,
    BOOKABLE INT,
    AVAILABLE INT
);
CREATE TABLE DISH (
    DISH_ID INT AUTO_INCREMENT PRIMARY KEY,
    DISH_NAME VARCHAR(20) NOT NULL,
    DISH_PRICE DECIMAL(12, 2) NOT NULL,
    DISH_TASTE VARCHAR(20) NOT NULL
);
CREATE TABLE MYORDER (
    TABLE_ID INT,
    DISH_ID INT,
    CONSUMPTION_RECORD_ID INT,
    ORDER_TIME TIMESTAMP,
    ORDER_STATUS VARCHAR(20) NOT NULL,
    FOREIGN KEY (TABLE_ID) REFERENCES MYTABLE(TABLE_ID),
    FOREIGN KEY (DISH_ID) REFERENCES DISH(DISH_ID),
    PRIMARY KEY (TABLE_ID, DISH_ID, ORDER_TIME)
);
CREATE TABLE BOOK (
    TABLE_ID INT,
    CUSTOMER_ID INT,
    BOOK_TIME TIMESTAMP,
    BOOK_NUMBER INT CHECK (BOOK_NUMBER >= 1),
    BOOK_STATUS VARCHAR(20) NOT NULL,
    BOOK_REQUEMENT VARCHAR(50),
    BOOK_NOTE VARCHAR(50),
    FOREIGN KEY (TABLE_ID) REFERENCES MYTABLE(TABLE_ID),
    PRIMARY KEY (TABLE_ID, CUSTOMER_ID, BOOK_TIME)
);

