CREATE TABLE CUSTOMER (
    CUSTOMER_ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(20) NOT NULL,
    ID CHAR(20),
    GENDER CHAR(2),
    PHONE VARCHAR(20) NOT NULL,
    CREDIT_GRADE VARCHAR(20) NOT NULL ,
    MEMBER_GRADE VARCHAR(20) NOT NULL 
);

CREATE TABLE BILL (
    BILL_ID INT AUTO_INCREMENT PRIMARY KEY,
    ROOM_COST DECIMAL(12,2),
    FOOD_COST DECIMAL(12,2),
    OTHER_COST DECIMAL(12,2),
    SUM_COST DECIMAL(12,2),
    BILL_TYPE VARCHAR(20),
    INVOICE_NUMBER VARCHAR(20),
    CUSTOMER_ID INT,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

CREATE TABLE ROOMTYPE (
    TYPE_ID INT AUTO_INCREMENT PRIMARY KEY,
    TYPE_NAME VARCHAR(20) NOT NULL,
    PRICE DECIMAL(10,2) CHECK (PRICE >= 0),
    NOTE VARCHAR(50),
    REMAINING INT
);

CREATE TABLE ROOM (
    ROOM_ID INT AUTO_INCREMENT PRIMARY KEY,
    TYPE_ID INT,
    ROOM_NUMBER INT NOT NULL,
    ROOM_PHONE VARCHAR(20) NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    FOREIGN KEY (TYPE_ID) REFERENCES ROOMTYPE(TYPE_ID)
);

CREATE TABLE PAY (
    CUSTOMER_ID INT,
    BILL_ID INT,
    PAY_METHOD VARCHAR(20),
    PAY_TIME TIMESTAMP,
    PAY_AMOUNT DECIMAL(12,2),
    PAY_STATUS VARCHAR(20),
    PRIMARY KEY (CUSTOMER_ID, BILL_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY (BILL_ID) REFERENCES BILL(BILL_ID)
);

CREATE TABLE CLEAN (
    ROOM_ID INT,
    EMPLOYEE_ID INT,
    CLEANING_TIME TIMESTAMP,
    PRIMARY KEY (ROOM_ID, EMPLOYEE_ID, CLEANING_TIME),
    FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ROOM_ID)
);

CREATE TABLE CHECKIN (
    CUSTOMER_ID INT,
    ROOM_ID INT,
    CHECKIN_TIME TIMESTAMP,
    CHECKOUT_TIME TIMESTAMP,
    PRIMARY KEY (CUSTOMER_ID, ROOM_ID, CHECKIN_TIME),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ROOM_ID)
);

CREATE TABLE ROOMORDER (
    ORDER_ID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID INT,
    TYPE_ID INT,
    EMPLOYEE_ID INT,
    ORDER_STATUS VARCHAR(20) NOT NULL,
    CREATE_TIME TIMESTAMP,
    CUSTOMER_NUM INT,
    EXPECT_IN_TIME DATE,
    EXPECT_OUT_TIME DATE,
    PRICE DECIMAL(12,2) CHECK (PRICE >= 0),
    NOTE VARCHAR(20),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY (TYPE_ID) REFERENCES ROOMTYPE(TYPE_ID)
);

CREATE TABLE CONSUMPTIONRECORDS (
    CONSUME_ID INT AUTO_INCREMENT PRIMARY KEY,
    ROOM_ID INT,
    CONSUME_TYPE VARCHAR(20),
    CONSUME_TIME TIMESTAMP,
    CONSUME_AMOUNT DECIMAL(12,2),
    FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ROOM_ID)
);
