CREATE TABLE PARKINGSPACE (
    PARKING_SPACE_ID INT AUTO_INCREMENT PRIMARY KEY,
    TYPE VARCHAR(20),
    AREA VARCHAR(20),
    STATUS VARCHAR(20),
    MEMBER_PRICE DECIMAL(12, 2),
    NOT_MEMBER_PRICE DECIMAL(12, 2)
);
CREATE TABLE CAR (
    CAR_NUMBER VARCHAR(20) PRIMARY KEY,
    CUSTOMER_ID INT
);
CREATE TABLE PARK (
    PARKING_SPACE_ID INT,
    CAR_NUMBER VARCHAR(20),
    PARKING_ENTER_TIME TIMESTAMP,
    PARKING_EXIST_TIME TIMESTAMP,
    FOREIGN KEY (PARKING_SPACE_ID) REFERENCES PARKINGSPACE(PARKING_SPACE_ID),
    FOREIGN KEY (CAR_NUMBER) REFERENCES CAR(CAR_NUMBER),
    PRIMARY KEY (PARKING_SPACE_ID, CAR_NUMBER, PARKING_ENTER_TIME)
);
