CREATE TABLE DEPARTMENT (
    DEPARTMENT_ID INT AUTO_INCREMENT PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR(20),
    NUMBER_OF_PEOPLE INT
);
CREATE TABLE POST (
    POST_ID INT AUTO_INCREMENT PRIMARY KEY,
    POST_NAME VARCHAR(12),
    DEPARTMENT_ID INT,
    POSITION_LEVEL VARCHAR(5),
    POSITION_SALARY INT,
    PAYMENT_TYPE VARCHAR(20),
    PAYMENT_BASE VARCHAR(20),
    INSURANCE VARCHAR(20),
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(DEPARTMENT_ID)
);
CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(10),
    SEX VARCHAR(4),
    AGE INT CHECK (AGE >= 0),
    POST_ID INT,
    ENTRY_TIME DATE,
    PHONE_NUMBER VARCHAR(20),
    BASE_PAY INT,
    PASSWORD VARCHAR(40),
    BANK_NAME VARCHAR(20),
    CREDIT_CARD_NUMBER VARCHAR(20),
    ACCOUNT VARCHAR(20),
    FOREIGN KEY (POST_ID) REFERENCES POST(POST_ID)
);
CREATE TABLE APPLICATION (
    APPLICATION_ID INT AUTO_INCREMENT PRIMARY KEY,
    APPLICATION_TIME DATE,
    APPLICATION_TYPE VARCHAR(7),
    APPLICATION_CONTENT VARCHAR(50),
    IF_APPROVE VARCHAR(20),
    EMPLOYEE_ID INT,
    DEPARTMENT_ID INT,
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID),
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(DEPARTMENT_ID)
);
